import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

import '../../../const/const.dart';
import '../../../models/message_model.dart';
import 'chat_states.dart';

class ChatCubit extends Cubit<ChatStates> {
  ChatCubit() : super(ChatIntialState());

  static ChatCubit get(context) => BlocProvider.of(context);

  String? message;

  Future<void> userSendMessage(String message, String serviceId) async {
    MessageModel messageModel = MessageModel(
      dateTime: DateTime.now().toString(),
      message: message,
      senderId: uId,
      serviceId: serviceId,
      isSeen: false,
    );
    print(uId);
    FirebaseFirestore.instance
        .collection('users')
        .doc(uId)
        .collection('chats')
        .doc(serviceId)
        .set({'exist': true}).then((value) {
      FirebaseFirestore.instance
          .collection('users')
          .doc(uId)
          .collection('chats')
          .doc(serviceId)
          .collection('messages')
          .add(messageModel.toMap())
          .then((value) {
        message = message;
        emit(ChatUserSendMessageSuccessState());
      }).catchError((error) {
        print(error.toString());
        emit(SocialSendMessageErrorState());
      });
    });
  }

  Future<void> botSendMessage(String message, String serviceId) async {
    MessageModel messageModel = MessageModel(
      dateTime: DateTime.now().toString(),
      message: message,
      senderId: serviceId,
      serviceId: serviceId,
      isSeen: false,
    );
    print(uId);
    FirebaseFirestore.instance
        .collection('users')
        .doc(uId)
        .collection('chats')
        .doc(serviceId)
        .set({'exist': true}).then((value) {
      FirebaseFirestore.instance
          .collection('users')
          .doc(uId)
          .collection('chats')
          .doc(serviceId)
          .collection('messages')
          .add(messageModel.toMap())
          .then((value) {
        emit(ChatBotSendMessageSuccessState());
      }).catchError((error) {
        print(error.toString());
        emit(SocialSendMessageErrorState());
      });
    });
  }

  List<MessageModel> messages = [];

  Future<void> getMessages(String serviceId) async {
    print('get');
    FirebaseFirestore.instance
        .collection('users')
        .doc(uId)
        .collection('chats')
        .doc(serviceId)
        .collection('messages')
        .orderBy('dateTime', descending: true)
        .snapshots()
        .listen((event) {
      messages = [];
      event.docs.forEach((element) {
        messages.add(MessageModel.fromJson(element.data()));
      });
      emit(ChatGetAllMessagesSuccessState());
    });
  }


  // bool isWrote = false;
  // Autogenerated? responseModel;
  //
  // String? licenseNumber, licenseType, government;
  // int? violationValue;
  // bool? isExist;
  // Future<void> dliSequence(String message, String serviceId) async {
  //
  //   if (licenseNumber != null) {
  //     if (licenseType != null) {
  //       if(government != null){
  //
  //       }
  //       else{
  //         DioHelper.getData(query: message).then((value) {
  //           responseModel = Autogenerated.fromJson(value.data);
  //           if (responseModel!.entities!.governmentGovernment?[0].name ==
  //               'government') {
  //             government =
  //                 responseModel!.entities!.governmentGovernment?[0].value;
  //             FirebaseFirestore.instance.collection('licenses').doc(licenseNumber).get().then((value) {
  //               violationValue =  value.get('violationValue');
  //             }).then((value) {
  //               botSendMessage('اجمالى المخالفات $violationValue جنية مصري ', serviceId);
  //             });
  //
  //           } else {
  //             botSendMessage(
  //                 'عذرا هذا ليست محافظة مسجلة لرخصة صالحة رجاء ادخل مرة اخري', serviceId);
  //           }
  //           emit(ChatSuccessResponseState());
  //         }).catchError((error) {
  //           emit(ChatErrorResponseState());
  //         });
  //       }
  //     } else {
  //       print(message);
  //       DioHelper.getData(query: message).then((value) {
  //         print(value.data);
  //
  //         responseModel = Autogenerated.fromJson(value.data);
  //         print(responseModel);
  //         print(responseModel?.entities?.licenseTypeLicenseType?[0].value);
  //         if (responseModel?.entities?.licenseTypeLicenseType?[0].name ==
  //             'licenseType') {
  //           licenseType =
  //               responseModel?.entities?.licenseTypeLicenseType?[0].value;
  //           botSendMessage('رجاء ادخل المحافظة التابع لها', serviceId);
  //         } else if(responseModel?.entities?.licenseTypeLicenseType?[0].name == null) {
  //           botSendMessage(
  //               'عذرا هذا ليس نوع رخصة صالح رجاء ادخل مرة اخري', serviceId);
  //         }else {
  //           botSendMessage(
  //               'عذرا هذا ليس نوع رخصة صالح رجاء ادخل مرة اخري', serviceId);
  //         }
  //         emit(ChatSuccessResponseState());
  //       }).catchError((error) {
  //         print(error);
  //         emit(ChatErrorResponseState());
  //       });
  //     }
  //   } else {
  //     DioHelper.getData(query: message).then((value) {
  //       responseModel = Autogenerated.fromJson(value.data);
  //       if (responseModel!.entities!.licenseNumberLicenseNumber?[0].name ==
  //           'licenseNumber' &&
  //           responseModel!
  //               .entities!.licenseNumberLicenseNumber?[0].value!.length ==
  //               14) {
  //         FirebaseFirestore.instance.collection('licenses').get().then((licenses) {
  //           if (licenses.docs.isNotEmpty) {
  //             licenses.docs.forEach((license) {
  //               print(license.id);
  //               print(responseModel!.entities!.licenseNumberLicenseNumber?[0].value);
  //               if(license.id == responseModel!.entities!.licenseNumberLicenseNumber?[0].value){
  //                 isExist = true;
  //               }else{
  //                 isExist = false;
  //               }
  //             });
  //           }
  //           if(isExist!){
  //             licenseNumber =
  //                 responseModel!.entities!.licenseNumberLicenseNumber?[0].value;
  //             botSendMessage('رجاء ادخل نوع الرخصة', serviceId);
  //
  //           }else{
  //             botSendMessage('هذه الرخصة غير موجودة رجاء ادخال رقم اخر', serviceId);
  //           }
  //         });
  //
  //       } else {
  //         botSendMessage(
  //             'عذرا هذا ليس رقم رخصة صالح رجاء ادخل مرة اخري', serviceId);
  //       }
  //       emit(ChatSuccessResponseState());
  //     }).catchError((error) {
  //       emit(ChatErrorResponseState());
  //     });
  //   }
  // }
  //
  // TravelModel? travelModel;
  //
  //
  // String? startStation, endStation,dateTime,answer;
  //
  // Future<void> travelSequence(String message, String serviceId,BuildContext context) async {
  //
  //   if (startStation != null) {
  //     if (endStation != null) {
  //       if(dateTime != null){
  //
  //       }
  //       else{
  //
  //       }
  //     }
  //     else {
  //       print(message);
  //       DioHelper.getTravelData(query: message).then((value) {
  //         travelModel = TravelModel.fromJson(value.data);
  //         print(travelModel);
  //         print(travelModel?.entities?.stationStation?[0].value);
  //         if (travelModel?.entities?.stationStation?[0].name ==
  //             'station') {
  //           endStation =
  //               travelModel?.entities?.stationStation?[0].value;
  //           botSendMessage('رجاء ادخل موعد السفر', serviceId).then((value) {
  //             DatePicker.showDateTimePicker(
  //                 context,
  //                 showTitleActions: true,
  //                 minTime:  DateTime(2023, 2, 13),
  //                 maxTime: DateTime(2023,4,13),
  //                 currentTime: DateTime.now(),
  //                 onConfirm: (date){
  //                   dateTime = date.toString();
  //                 },
  //                 locale: LocaleType.ar
  //             ).then((value) {
  //               TicketModel ticketModel = TicketModel(
  //                   startStation: startStation,
  //                   endStation: endStation,
  //                   startDate:dateTime.toString(),
  //                   ticketPrice: '30'
  //               );
  //               FirebaseFirestore.instance.collection('Tickets').add(ticketModel.toJson()).then((value) {
  //                 botSendMessage('تم حجز القطار المتجه من محطة $startStation الي محطة $endStation فى الوقت $dateTime وسعر التذكرة 30 جنية مصري', serviceId);
  //               });
  //             });
  //           });
  //
  //
  //         } else {
  //           botSendMessage(
  //               'عذرا هذا ليس اسم محطة صالح رجاء ادخل اسم محطة الوصول', serviceId);
  //         }
  //         emit(ChatSuccessResponseState());
  //       }).catchError((error) {
  //         print(error);
  //         emit(ChatErrorResponseState());
  //       });
  //     }
  //   } else {
  //     DioHelper.getTravelData(query: message).then((value) {
  //       print(value.data);
  //       print('-----------------------');
  //       travelModel = TravelModel.fromJson(value.data);
  //       print(responseModel??'xxxxxxxxxxxxxxxx');
  //       if (travelModel?.entities?.stationStation?[0].name ==
  //           'station') {
  //         startStation =
  //             travelModel?.entities?.stationStation?[0].value;
  //         botSendMessage('رجاء ادخل محطة الوصول', serviceId);
  //
  //
  //
  //       } else {
  //         botSendMessage(
  //             'عذرا هذا ليس اسم محطة صالح رجاء ادخل اسم محطة القيام', serviceId);
  //       }
  //       emit(ChatSuccessResponseState());
  //     }).catchError((error) {
  //       emit(ChatErrorResponseState());
  //     });
  //   }
  // }
}